jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MyPy Check
        uses: jpetrucciani/mypy-check@0.910
        with:
          path: "./staffeli_nt"
